require 'Items/SuburbsDistributions'
require 'Items/Distributions'

table.insert(ProceduralDistributions["list"]["ArmyHangarTools"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["ArmyHangarTools"].items, 1);
table.insert(ProceduralDistributions["list"]["ArmyHangarTools"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["ArmyHangarTools"].items, 1);
table.insert(ProceduralDistributions["list"]["ArmyHangarTools"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["ArmyHangarTools"].items, 1);
table.insert(ProceduralDistributions["list"]["ArmyHangarTools"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["ArmyHangarTools"].items, 1);
table.insert(ProceduralDistributions["list"]["ArmyHangarTools"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["ArmyHangarTools"].items, 1);

table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 1);
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 1);
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 1);
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 1);
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 1);

table.insert(ProceduralDistributions["list"]["ArmyStorageElectronics"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["ArmyStorageElectronics"].items, 1);
table.insert(ProceduralDistributions["list"]["ArmyStorageElectronics"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["ArmyStorageElectronics"].items, 1);
table.insert(ProceduralDistributions["list"]["ArmyStorageElectronics"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["ArmyStorageElectronics"].items, 1);
table.insert(ProceduralDistributions["list"]["ArmyStorageElectronics"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["ArmyStorageElectronics"].items, 1);
table.insert(ProceduralDistributions["list"]["ArmyStorageElectronics"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["ArmyStorageElectronics"].items, 1);

table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, 0.03);
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, 0.03);
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, 0.03);
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, 0.03);
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, 0.03);

table.insert(ProceduralDistributions["list"]["CrateElectronics"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["CrateElectronics"].items, 2);
table.insert(ProceduralDistributions["list"]["CrateElectronics"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["CrateElectronics"].items, 2);
table.insert(ProceduralDistributions["list"]["CrateElectronics"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["CrateElectronics"].items, 2);
table.insert(ProceduralDistributions["list"]["CrateElectronics"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["CrateElectronics"].items, 2);
table.insert(ProceduralDistributions["list"]["CrateElectronics"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["CrateElectronics"].items, 2);

table.insert(ProceduralDistributions["list"]["ElectronicStoreMisc"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["ElectronicStoreMisc"].items, 2);
table.insert(ProceduralDistributions["list"]["ElectronicStoreMisc"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["ElectronicStoreMisc"].items, 2);
table.insert(ProceduralDistributions["list"]["ElectronicStoreMisc"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["ElectronicStoreMisc"].items, 2);
table.insert(ProceduralDistributions["list"]["ElectronicStoreMisc"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["ElectronicStoreMisc"].items, 2);
table.insert(ProceduralDistributions["list"]["ElectronicStoreMisc"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["ElectronicStoreMisc"].items, 2);

table.insert(ProceduralDistributions["list"]["GeneratorRoom"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["GeneratorRoom"].items, 2);
table.insert(ProceduralDistributions["list"]["GeneratorRoom"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["GeneratorRoom"].items, 2);
table.insert(ProceduralDistributions["list"]["GeneratorRoom"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["GeneratorRoom"].items, 2);
table.insert(ProceduralDistributions["list"]["GeneratorRoom"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["GeneratorRoom"].items, 2);
table.insert(ProceduralDistributions["list"]["GeneratorRoom"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["GeneratorRoom"].items, 2);

table.insert(ProceduralDistributions["list"]["GigamartHouseElectronics"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["GigamartHouseElectronics"].items, 2);
table.insert(ProceduralDistributions["list"]["GigamartHouseElectronics"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["GigamartHouseElectronics"].items, 2);
table.insert(ProceduralDistributions["list"]["GigamartHouseElectronics"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["GigamartHouseElectronics"].items, 2);
table.insert(ProceduralDistributions["list"]["GigamartHouseElectronics"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["GigamartHouseElectronics"].items, 2);
table.insert(ProceduralDistributions["list"]["GigamartHouseElectronics"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["GigamartHouseElectronics"].items, 2);

table.insert(ProceduralDistributions["list"]["Hiker"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["Hiker"].items, 2);
table.insert(ProceduralDistributions["list"]["Hiker"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["Hiker"].items, 2);
table.insert(ProceduralDistributions["list"]["Hiker"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["Hiker"].items, 2);
table.insert(ProceduralDistributions["list"]["Hiker"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["Hiker"].items, 2);
table.insert(ProceduralDistributions["list"]["Hiker"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["Hiker"].items, 2);

table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, 0.03);
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, 0.03);
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, 0.03);
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, 0.03);
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, 0.03);

table.insert(ProceduralDistributions["list"]["MechanicShelfTools"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["MechanicShelfTools"].items, 2);
table.insert(ProceduralDistributions["list"]["MechanicShelfTools"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["MechanicShelfTools"].items, 2);
table.insert(ProceduralDistributions["list"]["MechanicShelfTools"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["MechanicShelfTools"].items, 2);
table.insert(ProceduralDistributions["list"]["MechanicShelfTools"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["MechanicShelfTools"].items, 2);
table.insert(ProceduralDistributions["list"]["MechanicShelfTools"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["MechanicShelfTools"].items, 2);

table.insert(ProceduralDistributions["list"]["MechanicSpecial"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["MechanicSpecial"].items, 2);
table.insert(ProceduralDistributions["list"]["MechanicSpecial"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["MechanicSpecial"].items, 2);
table.insert(ProceduralDistributions["list"]["MechanicSpecial"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["MechanicSpecial"].items, 2);
table.insert(ProceduralDistributions["list"]["MechanicSpecial"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["MechanicSpecial"].items, 2);
table.insert(ProceduralDistributions["list"]["MechanicSpecial"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["MechanicSpecial"].items, 2);

table.insert(ProceduralDistributions["list"]["OtherGeneric"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["OtherGeneric"].items, 2);
table.insert(ProceduralDistributions["list"]["OtherGeneric"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["OtherGeneric"].items, 2);
table.insert(ProceduralDistributions["list"]["OtherGeneric"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["OtherGeneric"].items, 2);
table.insert(ProceduralDistributions["list"]["OtherGeneric"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["OtherGeneric"].items, 2);
table.insert(ProceduralDistributions["list"]["OtherGeneric"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["OtherGeneric"].items, 2);

table.insert(ProceduralDistributions["list"]["RandomFiller"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["RandomFiller"].items, 2);
table.insert(ProceduralDistributions["list"]["RandomFiller"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["RandomFiller"].items, 2);
table.insert(ProceduralDistributions["list"]["RandomFiller"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["RandomFiller"].items, 2);
table.insert(ProceduralDistributions["list"]["RandomFiller"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["RandomFiller"].items, 2);
table.insert(ProceduralDistributions["list"]["RandomFiller"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["RandomFiller"].items, 2);

table.insert(ProceduralDistributions["list"]["StoreShelfElectronics"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["StoreShelfElectronics"].items, 2);
table.insert(ProceduralDistributions["list"]["StoreShelfElectronics"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["StoreShelfElectronics"].items, 2);
table.insert(ProceduralDistributions["list"]["StoreShelfElectronics"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["StoreShelfElectronics"].items, 2);
table.insert(ProceduralDistributions["list"]["StoreShelfElectronics"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["StoreShelfElectronics"].items, 2);
table.insert(ProceduralDistributions["list"]["StoreShelfElectronics"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["StoreShelfElectronics"].items, 2);

table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, 2);
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, 2);
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, 2);
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, 2);
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, 2);

table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, 2);
table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, 2);
table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, 2);
table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, 2);
table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, 2);

table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.08);
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.08);
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.08);
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.08);
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.08);

table.insert(ProceduralDistributions["list"]["CrateTools"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["CrateTools"].items, 1);
table.insert(ProceduralDistributions["list"]["CrateTools"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["CrateTools"].items, 1);
table.insert(ProceduralDistributions["list"]["CrateTools"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["CrateTools"].items, 1);
table.insert(ProceduralDistributions["list"]["CrateTools"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["CrateTools"].items, 1);
table.insert(ProceduralDistributions["list"]["CrateTools"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["CrateTools"].items, 1);

table.insert(ProceduralDistributions["list"]["EngineerTools"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["EngineerTools"].items, 1);
table.insert(ProceduralDistributions["list"]["EngineerTools"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["EngineerTools"].items, 1);
table.insert(ProceduralDistributions["list"]["EngineerTools"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["EngineerTools"].items, 1);
table.insert(ProceduralDistributions["list"]["EngineerTools"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["EngineerTools"].items, 1);
table.insert(ProceduralDistributions["list"]["EngineerTools"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["EngineerTools"].items, 1);

table.insert(ProceduralDistributions["list"]["FactoryLockers"].items, "CTorch.CrankTorch1");
table.insert(ProceduralDistributions["list"]["FactoryLockers"].items, 0.5);
table.insert(ProceduralDistributions["list"]["FactoryLockers"].items, "CTorch.CrankTorch2");
table.insert(ProceduralDistributions["list"]["FactoryLockers"].items, 0.5);
table.insert(ProceduralDistributions["list"]["FactoryLockers"].items, "CTorch.CrankTorch3");
table.insert(ProceduralDistributions["list"]["FactoryLockers"].items, 0.5);
table.insert(ProceduralDistributions["list"]["FactoryLockers"].items, "CTorch.CrankTorch4");
table.insert(ProceduralDistributions["list"]["FactoryLockers"].items, 0.5);
table.insert(ProceduralDistributions["list"]["FactoryLockers"].items, "CTorch.CrankTorch5");
table.insert(ProceduralDistributions["list"]["FactoryLockers"].items, 0.5);
